# SPDX-License-Identifier: BSD-2-Clause
# tpm_ftpm_tee talks to the fTPM TA that tee-supplicant loads on-demand from
# /lib/firmware/optee. Block modalias autoload so the driver is not probed
# before tee-supplicant is up (that first probe fails ITEM_NOT_FOUND / -EINVAL
# and logs an error every boot). tee-supplicant@.service loads it by name,
# which ignores this blacklist.
blacklist tpm_ftpm_tee
